[build]
    publish = "public"
    command = "hugo"

[build.environment]
    HUGO_VERSION = "0.81.0"
    HUGO_THEME = "repo"
    HUGO_BASEURL = "https://insightstream.dev"

[context.production.environment]
    HUGO_VERSION = "0.81.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"