[build]
    publish = "public"
    command = "hugo --themesDir themes/uBlogger"

[build.environment]
    HUGO_VERSION = "0.81.0/extended"
    HUGO_THEME = "repo"
    HUGO_BASEURL = "https://insightstream.dev"

